"""HTTP route contract, kept in the original registration order."""

ROUTES = [{'name': 'api_heartbeat', 'method': 'post', 'path': '/api/heartbeat', 'options': {}},
 {'name': 'healthz',
  'method': 'get',
  'path': '/healthz',
  'options': {'include_in_schema': False}},
 {'name': 'read_index', 'method': 'get', 'path': '/', 'options': {}},
 {'name': 'read_favicon',
  'method': 'get',
  'path': '/favicon.ico',
  'options': {'include_in_schema': False}},
 {'name': 'read_favicon_svg',
  'method': 'get',
  'path': '/favicon.svg',
  'options': {'include_in_schema': False}},
 {'name': 'read_apple_touch_icon',
  'method': 'get',
  'path': '/apple-touch-icon.png',
  'options': {'include_in_schema': False}},
 {'name': 'read_apple_touch_icon',
  'method': 'get',
  'path': '/apple-touch-icon-precomposed.png',
  'options': {'include_in_schema': False}},
 {'name': 'format_fraction_style',
  'method': 'post',
  'path': '/api/format/fractions',
  'options': {}},
 {'name': 'upload_image', 'method': 'post', 'path': '/api/upload', 'options': {}},
 {'name': 'ocr_formula', 'method': 'post', 'path': '/api/ocr', 'options': {}},
 {'name': 'ai_solve', 'method': 'post', 'path': '/api/ai/solve', 'options': {}},
 {'name': 'get_settings', 'method': 'get', 'path': '/api/settings', 'options': {}},
 {'name': 'save_settings', 'method': 'post', 'path': '/api/settings/save', 'options': {}},
 {'name': 'get_version_info', 'method': 'get', 'path': '/api/version', 'options': {}},
 {'name': 'check_version_update',
  'method': 'get',
  'path': '/api/version/check-update',
  'options': {}},
 {'name': 'render_tikz_endpoint', 'method': 'post', 'path': '/api/render_tikz', 'options': {}},
 {'name': 'correct_tikz_endpoint',
  'method': 'post',
  'path': '/api/correct_tikz',
  'options': {}},
 {'name': 'draw_tikz_workbench_endpoint',
  'method': 'post',
  'path': '/api/ai/draw_tikz',
  'options': {}},
 {'name': 'draw_tikz_from_image_endpoint',
  'method': 'post',
  'path': '/api/ai/draw_tikz_from_image',
  'options': {}},
 {'name': 'list_questions', 'method': 'get', 'path': '/api/questions', 'options': {}},
 {'name': 'check_question_duplicates',
  'method': 'post',
  'path': '/api/questions/check-duplicates',
  'options': {}},
 {'name': 'get_question',
  'method': 'get',
  'path': '/api/questions/{question_id}',
  'options': {}},
 {'name': 'create_question', 'method': 'post', 'path': '/api/questions', 'options': {}},
 {'name': 'update_question',
  'method': 'put',
  'path': '/api/questions/{question_id}',
  'options': {}},
 {'name': 'update_question_figure_align',
  'method': 'post',
  'path': '/api/questions/{question_id}/figure_align',
  'options': {}},
 {'name': 'update_question_figure_layout',
  'method': 'post',
  'path': '/api/questions/{question_id}/figure_layout',
  'options': {}},
 {'name': 'get_associated_questions',
  'method': 'get',
  'path': '/api/questions/{question_id}/associated',
  'options': {}},
 {'name': 'associate_questions_endpoint',
  'method': 'post',
  'path': '/api/questions/{question_id}/associate',
  'options': {}},
 {'name': 'remove_association',
  'method': 'delete',
  'path': '/api/questions/{question_id}/associated',
  'options': {}},
 {'name': 'delete_question',
  'method': 'delete',
  'path': '/api/questions/{question_id}',
  'options': {}},
 {'name': 'get_metadata_config',
  'method': 'get',
  'path': '/api/config/metadata',
  'options': {}},
 {'name': 'get_curriculum_preset_config',
  'method': 'get',
  'path': '/api/config/curriculum-presets/{version}',
  'options': {}},
 {'name': 'save_metadata_config',
  'method': 'post',
  'path': '/api/config/metadata',
  'options': {}},
 {'name': 'get_db_stats', 'method': 'get', 'path': '/api/stats', 'options': {}},
 {'name': 'list_categories', 'method': 'get', 'path': '/api/categories', 'options': {}},
 {'name': 'ai_classify', 'method': 'post', 'path': '/api/ai/classify', 'options': {}},
 {'name': 'upload_tex_source',
  'method': 'post',
  'path': '/api/upload/tex-source',
  'options': {}},
 {'name': 'upload_batch_images', 'method': 'post', 'path': '/api/upload/batch', 'options': {}},
 {'name': 'ai_parse_paper', 'method': 'post', 'path': '/api/ai/parse-paper', 'options': {}},
 {'name': 'get_sources', 'method': 'get', 'path': '/api/sources', 'options': {}},
 {'name': 'shutdown_server', 'method': 'post', 'path': '/api/shutdown', 'options': {}},
 {'name': 'manual_crop_pdf',
  'method': 'post',
  'path': '/api/ai/manual-crop-pdf',
  'options': {}},
 {'name': 'ai_select_paper', 'method': 'post', 'path': '/api/paper/ai-select', 'options': {}},
 {'name': 'upload_pdf_task', 'method': 'post', 'path': '/api/upload/pdf-task', 'options': {}},
 {'name': 'upload_docx_task',
  'method': 'post',
  'path': '/api/upload/docx-task',
  'options': {}},
 {'name': 'get_pdf_task_status',
  'method': 'get',
  'path': '/api/tasks/{task_id}/status',
  'options': {}},
 {'name': 'cancel_pdf_task',
  'method': 'post',
  'path': '/api/tasks/{task_id}/cancel',
  'options': {}},
 {'name': 'clear_temp_crops',
  'method': 'post',
  'path': '/api/ai/clear-temp-crops',
  'options': {}},
 {'name': 'get_paper_questions',
  'method': 'get',
  'path': '/api/paper/questions',
  'options': {}},
 {'name': 'save_paper', 'method': 'post', 'path': '/api/paper/save', 'options': {}},
 {'name': 'list_papers', 'method': 'get', 'path': '/api/papers', 'options': {}},
 {'name': 'get_paper_detail',
  'method': 'get',
  'path': '/api/papers/{paper_id}',
  'options': {}},
 {'name': 'delete_paper', 'method': 'delete', 'path': '/api/papers/{paper_id}', 'options': {}},
 {'name': 'export_paper_tex',
  'method': 'post',
  'path': '/api/paper/export/tex',
  'options': {}},
 {'name': 'export_paper_bundle',
  'method': 'post',
  'path': '/api/paper/export/bundle',
  'options': {}},
 {'name': 'export_paper_pdf',
  'method': 'post',
  'path': '/api/paper/export/pdf',
  'options': {}},
 {'name': 'get_pandoc_runtime_status',
  'method': 'get',
  'path': '/api/runtime/pandoc/status',
  'options': {}},
 {'name': 'install_pandoc_runtime',
  'method': 'post',
  'path': '/api/runtime/pandoc/install',
  'options': {}},
 {'name': 'get_pandoc_install_status',
  'method': 'get',
  'path': '/api/runtime/pandoc/install/{task_id}',
  'options': {}},
 {'name': 'export_paper_word',
  'method': 'post',
  'path': '/api/paper/export/word',
  'options': {}}]


def register_routes(app, resolve):
    """Keep direct application registrations and their original override provider."""
    for route in ROUTES:
        app.add_api_route(route["path"], resolve(route["name"]), methods=[route["method"].upper()], **route["options"])
